/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import app.bolivia.swing.JCTextField;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ReturnBooks extends javax.swing.JFrame {

    /**
     * Creates new form IssueBooks
     */
    public ReturnBooks() {
        initComponents();
    }
    public void getIssueBookDetails() {

        int bookID;
        String studentID;
    try {
         bookID = Integer.parseInt(txt_bookID.getText());
         studentID = txt_studentID.getText();
         try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from issue_book_details where book_id = ? and student_id=? and status = ?");
            pst.setInt(1,bookID);
            pst.setString(2, studentID);
            pst.setString(3,"pending");
            ResultSet rs = pst.executeQuery();
            if (!rs.next())
            {
                JOptionPane.showMessageDialog(this, "No record found!");
                  lbl_issueID.setText("");
                  lbl_bookName.setText("");
                  lbl_studentName.setText("");
                  lbl_issueDate.setText("");
                  lbl_dueDate.setText("");
            }
            else
            {
           
                  lbl_issueID.setText(rs.getString("id"));
                  lbl_bookName.setText(rs.getString("book_name"));;
                  lbl_studentName.setText(rs.getString("student_name"));
                  lbl_issueDate.setText(rs.getString("issue_date"));
                  lbl_dueDate.setText(rs.getString("due_date"));
        
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter number for BookID!");
        txt_bookID.setText("");
    }
  
    }
    
    // return book check
    public boolean returnBook() {
        boolean isReturned = false;
        int issueID;
        try {
            issueID = Integer.parseInt(lbl_issueID.getText());          
        } catch (NumberFormatException e) {
            return false;
        }
        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst=con.prepareStatement("update issue_book_details set status = ? where id=?");
            pst.setString(1, "Returned");
            pst.setInt(2,issueID);
            int rowCount = pst.executeUpdate();
            if (rowCount>0)
            {
                isReturned = true;
                  lbl_issueID.setText("");
                  lbl_bookName.setText("");
                  lbl_studentName.setText("");
                  lbl_issueDate.setText("");
                  lbl_dueDate.setText("");
            }
            else
            {
           
                  lbl_issueID.setText("");
                  lbl_bookName.setText("");
                  lbl_studentName.setText("");
                  lbl_issueDate.setText("");
                  lbl_dueDate.setText("");
        
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return isReturned;
    }

public void updateBookQuantity() {
    int bookId = Integer.parseInt(txt_bookID.getText());
    try {
        Connection con = DBConnection.getConnection();
        String sql = "update book_details set quantity = quantity +1 where book_id=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1,bookId);
        int rowCount = pst.executeUpdate();
     
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_dueDate = new javax.swing.JLabel();
        lbl_issueID = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_studentName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        txt_bookID = new app.bolivia.swing.JCTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_studentID = new app.bolivia.swing.JCTextField();
        jLabel22 = new javax.swing.JLabel();
        btn_issueBook = new necesario.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_issueBook1 = new necesario.RSMaterialButtonCircle();
        rSButtonHover1 = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 214, 98));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("Issue Details");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 310, 110));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(2, 55));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 300, 3));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Issue Date:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Issue ID:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Book Name:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Student Name:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        lbl_dueDate.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lbl_dueDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lbl_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 200, 20));

        lbl_issueID.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lbl_issueID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lbl_issueID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 200, 20));

        lbl_bookName.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 200, 20));

        lbl_studentName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_studentName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 200, 20));

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Due Date:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        lbl_issueDate.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lbl_issueDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 200, 20));

        panel_main.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, 400, 800));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 26)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel18.setText("RETURN BOOK");
        panel_main.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 310, 110));

        jPanel17.setBackground(new java.awt.Color(255, 51, 0));
        jPanel17.setForeground(new java.awt.Color(255, 0, 0));
        jPanel17.setPreferredSize(new java.awt.Dimension(2, 55));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_main.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 300, 3));

        txt_bookID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        txt_bookID.setPlaceholder("Enter BookID...");
        txt_bookID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIDFocusLost(evt);
            }
        });
        txt_bookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIDActionPerformed(evt);
            }
        });
        panel_main.add(txt_bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, 270, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Book ID:");
        panel_main.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, -1, 20));

        txt_studentID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        txt_studentID.setPlaceholder("Enter StudentID...");
        txt_studentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIDFocusLost(evt);
            }
        });
        txt_studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentIDActionPerformed(evt);
            }
        });
        panel_main.add(txt_studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, 270, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Student ID:");
        panel_main.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, -1, 20));

        btn_issueBook.setBackground(new java.awt.Color(255, 51, 51));
        btn_issueBook.setText("Return Book");
        btn_issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issueBookActionPerformed(evt);
            }
        });
        panel_main.add(btn_issueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 220, 60));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("BACK");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        panel_main.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-3.png.png"))); // NOI18N
        panel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 460, 560));

        btn_issueBook1.setBackground(new java.awt.Color(102, 102, 255));
        btn_issueBook1.setText("FIND");
        btn_issueBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issueBook1ActionPerformed(evt);
            }
        });
        panel_main.add(btn_issueBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 220, 60));

        rSButtonHover1.setText("Search");
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        panel_main.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 90, 30));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txt_bookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIDActionPerformed

    private void txt_studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentIDActionPerformed

    private void btn_issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issueBookActionPerformed
        // TODO add your handling code here
        if (returnBook())
        {
            JOptionPane.showMessageDialog(this, "Returned Successfull");
            updateBookQuantity();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Returned fail");
        }
            
            
        
    }//GEN-LAST:event_btn_issueBookActionPerformed

    private void txt_bookIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIDFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_bookIDFocusLost

    private void txt_studentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIDFocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txt_studentIDFocusLost

    private void btn_issueBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issueBook1ActionPerformed
        // TODO add your handling code here:
     getIssueBookDetails();
    }//GEN-LAST:event_btn_issueBook1ActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
        new SearchIDIssue().setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooks().setVisible(true);
            }
        });
    }

    public JLabel getLbl_bookName() {
        return lbl_bookName;
    }

    public void setLbl_bookName(String input) {
        this.lbl_bookName.setText(input);
    }

    public JLabel getLbl_dueDate() {
        return lbl_dueDate;
    }

    public void setLbl_dueDate(String input) {
        this.lbl_dueDate.setText(input);
    }

    public JLabel getLbl_issueDate() {
        return lbl_issueDate;
    }

    public void setLbl_issueDate(String input) {
        this.lbl_issueDate.setText(input);
    }

    public JLabel getLbl_issueID() {
        return lbl_issueID;
    }

    public void setLbl_issueID(String input) {
        this.lbl_issueID.setText(input);
    }

    public JLabel getLbl_studentName() {
        return lbl_studentName;
    }

    public void setLbl_studentName(String input) {
        this.lbl_studentName.setText(input);
    }

    public void setTxt_bookID(String input) {
        this.txt_bookID.setText(input);
    }

    public void setTxt_studentID(String input) {
        this.txt_studentID.setText(input);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle btn_issueBook;
    private necesario.RSMaterialButtonCircle btn_issueBook1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_dueDate;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JLabel lbl_issueID;
    private javax.swing.JLabel lbl_studentName;
    private javax.swing.JPanel panel_main;
    private rojerusan.RSButtonHover rSButtonHover1;
    private app.bolivia.swing.JCTextField txt_bookID;
    private app.bolivia.swing.JCTextField txt_studentID;
    // End of variables declaration//GEN-END:variables
}
